#!/bin/bash

BASE=Bgsd6e
VORONOI=v20
WORKDIR=/Volumes/backupzeira/CALIFA/q043
PX1SUPERFITSDIR=${WORKDIR}/px1
VXXSUPERFITSDIR=${WORKDIR}/${VORONOI}/${BASE}
PX1EMLINESFITSDIR=${WORKDIR}/emlines/px1${BASE}
VXXEMLINESFITSDIR=${WORKDIR}/emlines/${VORONOI}${BASE}
GALAXIESFILE=/Users/lacerda/CALIFA/listALL.csv
#GALAXIESFILE=/Users/lacerda/CALIFA/listdebug.csv
GALAXIESIMGDIR=/Users/lacerda/CALIFA/images

OUTPUTDIR=.
IMGSUFFIX=png

for K in $( grep -v '^#' ${GALAXIESFILE} )
do
    echo $K
    PX1SUPERFITSSUFFIX="_synthesis_eBR_px1_q043.d14a512.ps03.k1.mE.CCM."
    PX1SUPERFITSFILE=${PX1SUPERFITSDIR}/${K}${PX1SUPERFITSSUFFIX}${BASE}.fits
    VXXSUPERFITSSUFFIX="_synthesis_eBR_v20_q043.d14a512.ps03.k1.mE.CCM."
    VXXSUPERFITSFILE=${VXXSUPERFITSDIR}/${K}${VXXSUPERFITSSUFFIX}${BASE}.fits
    PX1EMLINESFITSFILE=${PX1EMLINESFITSDIR}/${K}${PX1SUPERFITSSUFFIX}${BASE}.EML.MC100.fits
    VXXEMLINESFITSFILE=${VXXEMLINESFITSDIR}/${K}${VXXSUPERFITSSUFFIX}${BASE}.EML.MC100.fits
    GALAXYIMGFILE=${GALAXIESIMGDIR}/${K}.jpg
    
    ./comp.py --px1FitsFile=${PX1SUPERFITSFILE} \
        --px1EmLinesFitsFile=${PX1EMLINESFITSFILE} \
        --vxxFitsFile=${VXXSUPERFITSFILE} \
        --vxxEmLinesFitsFile=${VXXEMLINESFITSFILE} \
        --vxx=v20 \
        --galaxyImgFile=${GALAXYIMGFILE} \
        --outputImgSuffix=${IMGSUFFIX} \
        --outputDir=${OUTPUTDIR}
done
